# coding: utf-8

"""
    Sematext Cloud API

    API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.  # noqa: E501

    OpenAPI spec version: v3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import stcloud
from stcloud.api.tokens_api_controller_api import TokensApiControllerApi  # noqa: E501
from stcloud.rest import ApiException


class TestTokensApiControllerApi(unittest.TestCase):
    """TokensApiControllerApi unit test stubs"""

    def setUp(self):
        self.api = stcloud.api.tokens_api_controller_api.TokensApiControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_app_token(self):
        """Test case for create_app_token

        Create new app token  # noqa: E501
        """
        pass

    def test_delete_app_token1(self):
        """Test case for delete_app_token1

        Delete app token  # noqa: E501
        """
        pass

    def test_get_app_tokens1(self):
        """Test case for get_app_tokens1

        Get app available tokens  # noqa: E501
        """
        pass

    def test_regenerate_app_token(self):
        """Test case for regenerate_app_token

        Regenerate app token)  # noqa: E501
        """
        pass

    def test_update_app_token(self):
        """Test case for update_app_token

        Update app token (enable/disable)  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
