# coding: utf-8

"""
    Sematext Cloud API

    API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.  # noqa: E501

    OpenAPI spec version: v3

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import stcloud
from stcloud.api.metrics_api import MetricsApi  # noqa: E501
from stcloud.rest import ApiException


class TestMetricsApi(unittest.TestCase):
    """MetricsApi unit test stubs"""

    def setUp(self):
        self.api = stcloud.api.metrics_api.MetricsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_list_data_series_using_post1(self):
        """Test case for list_data_series_using_post1

        Get metrics data points for an app  # noqa: E501
        """
        pass

    def test_list_filters_using_post(self):
        """Test case for list_filters_using_post

        Get metrics filters and their values for an app  # noqa: E501
        """
        pass

    def test_list_metrics_keys_using_get1(self):
        """Test case for list_metrics_keys_using_get1

        Get metrics keys for an app  # noqa: E501
        """
        pass

    def test_list_metrics_using_get1(self):
        """Test case for list_metrics_using_get1

        Get metrics info for an app  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
