# coding: utf-8

"""
    Sematext Cloud API

    API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.  # noqa: E501

    OpenAPI spec version: v3

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import stcloud
from stcloud.api.alerts_api import AlertsApi  # noqa: E501
from stcloud.rest import ApiException


class TestAlertsApi(unittest.TestCase):
    """AlertsApi unit test stubs"""

    def setUp(self):
        self.api = stcloud.api.alerts_api.AlertsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_alert_using_post(self):
        """Test case for create_alert_using_post

        Create alert rule  # noqa: E501
        """
        pass

    def test_delete_alert_rule_using_delete(self):
        """Test case for delete_alert_rule_using_delete

        Delete alert rule  # noqa: E501
        """
        pass

    def test_disable_alert_rule_using_put(self):
        """Test case for disable_alert_rule_using_put

        Disable alert rule  # noqa: E501
        """
        pass

    def test_enable_alert_rule_using_put(self):
        """Test case for enable_alert_rule_using_put

        Enable alert rule  # noqa: E501
        """
        pass

    def test_get_alert_rules_for_app_using_get(self):
        """Test case for get_alert_rules_for_app_using_get

        Get alert rules for an app  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
