# coding: utf-8

"""
    Sematext Cloud API

    API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.  # noqa: E501

    OpenAPI spec version: v3

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import stcloud
from stcloud.api.tag_api_controller_api import TagApiControllerApi  # noqa: E501
from stcloud.rest import ApiException


class TestTagApiControllerApi(unittest.TestCase):
    """TagApiControllerApi unit test stubs"""

    def setUp(self):
        self.api = stcloud.api.tag_api_controller_api.TagApiControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_tag_names_using_get(self):
        """Test case for get_tag_names_using_get

        Gets tag names for the given application identifiers appearing in the given time frame.  # noqa: E501
        """
        pass

    def test_get_using_get2(self):
        """Test case for get_using_get2

        Gets values for specified tags for the given application identifiers appearing in the given time frame.  # noqa: E501
        """
        pass

    def test_get_using_get3(self):
        """Test case for get_using_get3

        Gets values for specified tags for the given application identifiers appearing in the given time frame.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
