# coding: utf-8

"""
    Sematext Cloud API Python Client

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from setuptools import setup, find_packages  # mypy: disable=W0611 # noqa:

NAME = "sematext-api-client-python"
VERSION = "0.4.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["urllib3 >= 1.15", "six >= 1.10", "certifi", "python-dateutil"]


with open("README.md", "r") as fh:
    long_description = fh.read()


setup(
    name=NAME,
    version=VERSION,
    description="Sematext Cloud API",
    author_email="",
    url="https://github.com/sematext/sematext-api-client-python",
    keywords=["Sematext", "Cloud", "API", "Monitoring", "Logging", "Metrics"],
    install_requires=REQUIRES,
    packages=find_packages(),
    include_package_data=True,
    long_description=long_description,
    long_description_content_type="text/markdown",
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: Apache Software License",
        "Operating System :: OS Independent",
    ]
)
