# coding: utf-8

"""
    Sematext Cloud API

    API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.  # noqa: E501

    OpenAPI spec version: v3

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class AlertRuleScheduleWeekdayDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'day': 'str',
        'index': 'int',
        'intervals': 'list[AlertRuleScheduleTimeRangeDto]',
        'label': 'str',
        'type': 'str'
    }

    attribute_map = {
        'day': 'day',
        'index': 'index',
        'intervals': 'intervals',
        'label': 'label',
        'type': 'type'
    }

    def __init__(self, day=None, index=None, intervals=None, label=None, type=None):  # noqa: E501
        """AlertRuleScheduleWeekdayDto - a model defined in Swagger"""  # noqa: E501

        self._day = None
        self._index = None
        self._intervals = None
        self._label = None
        self._type = None
        self.discriminator = None

        if day is not None:
            self.day = day
        if index is not None:
            self.index = index
        if intervals is not None:
            self.intervals = intervals
        if label is not None:
            self.label = label
        if type is not None:
            self.type = type

    @property
    def day(self):
        """Gets the day of this AlertRuleScheduleWeekdayDto.  # noqa: E501


        :return: The day of this AlertRuleScheduleWeekdayDto.  # noqa: E501
        :rtype: str
        """
        return self._day

    @day.setter
    def day(self, day):
        """Sets the day of this AlertRuleScheduleWeekdayDto.


        :param day: The day of this AlertRuleScheduleWeekdayDto.  # noqa: E501
        :type: str
        """

        self._day = day

    @property
    def index(self):
        """Gets the index of this AlertRuleScheduleWeekdayDto.  # noqa: E501


        :return: The index of this AlertRuleScheduleWeekdayDto.  # noqa: E501
        :rtype: int
        """
        return self._index

    @index.setter
    def index(self, index):
        """Sets the index of this AlertRuleScheduleWeekdayDto.


        :param index: The index of this AlertRuleScheduleWeekdayDto.  # noqa: E501
        :type: int
        """

        self._index = index

    @property
    def intervals(self):
        """Gets the intervals of this AlertRuleScheduleWeekdayDto.  # noqa: E501


        :return: The intervals of this AlertRuleScheduleWeekdayDto.  # noqa: E501
        :rtype: list[AlertRuleScheduleTimeRangeDto]
        """
        return self._intervals

    @intervals.setter
    def intervals(self, intervals):
        """Sets the intervals of this AlertRuleScheduleWeekdayDto.


        :param intervals: The intervals of this AlertRuleScheduleWeekdayDto.  # noqa: E501
        :type: list[AlertRuleScheduleTimeRangeDto]
        """

        self._intervals = intervals

    @property
    def label(self):
        """Gets the label of this AlertRuleScheduleWeekdayDto.  # noqa: E501


        :return: The label of this AlertRuleScheduleWeekdayDto.  # noqa: E501
        :rtype: str
        """
        return self._label

    @label.setter
    def label(self, label):
        """Sets the label of this AlertRuleScheduleWeekdayDto.


        :param label: The label of this AlertRuleScheduleWeekdayDto.  # noqa: E501
        :type: str
        """

        self._label = label

    @property
    def type(self):
        """Gets the type of this AlertRuleScheduleWeekdayDto.  # noqa: E501


        :return: The type of this AlertRuleScheduleWeekdayDto.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this AlertRuleScheduleWeekdayDto.


        :param type: The type of this AlertRuleScheduleWeekdayDto.  # noqa: E501
        :type: str
        """

        self._type = type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AlertRuleScheduleWeekdayDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AlertRuleScheduleWeekdayDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
