# coding: utf-8

"""
    Sematext Cloud API

    API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.  # noqa: E501

    OpenAPI spec version: v3

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class BasicOrganizationDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'auth_methods': 'list[BasicAuthMethodDto]',
        'name': 'str',
        'status': 'str',
        'uuid': 'str'
    }

    attribute_map = {
        'auth_methods': 'authMethods',
        'name': 'name',
        'status': 'status',
        'uuid': 'uuid'
    }

    def __init__(self, auth_methods=None, name=None, status=None, uuid=None):  # noqa: E501
        """BasicOrganizationDto - a model defined in Swagger"""  # noqa: E501

        self._auth_methods = None
        self._name = None
        self._status = None
        self._uuid = None
        self.discriminator = None

        if auth_methods is not None:
            self.auth_methods = auth_methods
        if name is not None:
            self.name = name
        if status is not None:
            self.status = status
        if uuid is not None:
            self.uuid = uuid

    @property
    def auth_methods(self):
        """Gets the auth_methods of this BasicOrganizationDto.  # noqa: E501


        :return: The auth_methods of this BasicOrganizationDto.  # noqa: E501
        :rtype: list[BasicAuthMethodDto]
        """
        return self._auth_methods

    @auth_methods.setter
    def auth_methods(self, auth_methods):
        """Sets the auth_methods of this BasicOrganizationDto.


        :param auth_methods: The auth_methods of this BasicOrganizationDto.  # noqa: E501
        :type: list[BasicAuthMethodDto]
        """

        self._auth_methods = auth_methods

    @property
    def name(self):
        """Gets the name of this BasicOrganizationDto.  # noqa: E501


        :return: The name of this BasicOrganizationDto.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this BasicOrganizationDto.


        :param name: The name of this BasicOrganizationDto.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def status(self):
        """Gets the status of this BasicOrganizationDto.  # noqa: E501


        :return: The status of this BasicOrganizationDto.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this BasicOrganizationDto.


        :param status: The status of this BasicOrganizationDto.  # noqa: E501
        :type: str
        """
        allowed_values = ["ACTIVE", "IN_REGISTRATION", "DISABLED", "EXPIRED", "INVITED", "DEMO"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"  # noqa: E501
                .format(status, allowed_values)
            )

        self._status = status

    @property
    def uuid(self):
        """Gets the uuid of this BasicOrganizationDto.  # noqa: E501


        :return: The uuid of this BasicOrganizationDto.  # noqa: E501
        :rtype: str
        """
        return self._uuid

    @uuid.setter
    def uuid(self, uuid):
        """Sets the uuid of this BasicOrganizationDto.


        :param uuid: The uuid of this BasicOrganizationDto.  # noqa: E501
        :type: str
        """

        self._uuid = uuid

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(BasicOrganizationDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BasicOrganizationDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
