# coding: utf-8

"""
    Sematext Cloud API

    API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.  # noqa: E501

    OpenAPI spec version: v3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CreateTokenDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'readable': 'bool',
        'writeable': 'bool'
    }

    attribute_map = {
        'name': 'name',
        'readable': 'readable',
        'writeable': 'writeable'
    }

    def __init__(self, name=None, readable=None, writeable=None):  # noqa: E501
        """CreateTokenDto - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._readable = None
        self._writeable = None
        self.discriminator = None
        if name is not None:
            self.name = name
        if readable is not None:
            self.readable = readable
        if writeable is not None:
            self.writeable = writeable

    @property
    def name(self):
        """Gets the name of this CreateTokenDto.  # noqa: E501


        :return: The name of this CreateTokenDto.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this CreateTokenDto.


        :param name: The name of this CreateTokenDto.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def readable(self):
        """Gets the readable of this CreateTokenDto.  # noqa: E501


        :return: The readable of this CreateTokenDto.  # noqa: E501
        :rtype: bool
        """
        return self._readable

    @readable.setter
    def readable(self, readable):
        """Sets the readable of this CreateTokenDto.


        :param readable: The readable of this CreateTokenDto.  # noqa: E501
        :type: bool
        """

        self._readable = readable

    @property
    def writeable(self):
        """Gets the writeable of this CreateTokenDto.  # noqa: E501


        :return: The writeable of this CreateTokenDto.  # noqa: E501
        :rtype: bool
        """
        return self._writeable

    @writeable.setter
    def writeable(self, writeable):
        """Sets the writeable of this CreateTokenDto.


        :param writeable: The writeable of this CreateTokenDto.  # noqa: E501
        :type: bool
        """

        self._writeable = writeable

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CreateTokenDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreateTokenDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
