# coding: utf-8

"""
    Sematext Cloud API

    API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.  # noqa: E501

    OpenAPI spec version: v3

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class FilterValue(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'agg_type': 'str',
        'filter_name': 'str',
        'key': 'str',
        'label': 'str',
        'name': 'str',
        'values': 'list[str]'
    }

    attribute_map = {
        'agg_type': 'aggType',
        'filter_name': 'filterName',
        'key': 'key',
        'label': 'label',
        'name': 'name',
        'values': 'values'
    }

    def __init__(self, agg_type=None, filter_name=None, key=None, label=None, name=None, values=None):  # noqa: E501
        """FilterValue - a model defined in Swagger"""  # noqa: E501

        self._agg_type = None
        self._filter_name = None
        self._key = None
        self._label = None
        self._name = None
        self._values = None
        self.discriminator = None

        if agg_type is not None:
            self.agg_type = agg_type
        if filter_name is not None:
            self.filter_name = filter_name
        if key is not None:
            self.key = key
        if label is not None:
            self.label = label
        if name is not None:
            self.name = name
        if values is not None:
            self.values = values

    @property
    def agg_type(self):
        """Gets the agg_type of this FilterValue.  # noqa: E501


        :return: The agg_type of this FilterValue.  # noqa: E501
        :rtype: str
        """
        return self._agg_type

    @agg_type.setter
    def agg_type(self, agg_type):
        """Sets the agg_type of this FilterValue.


        :param agg_type: The agg_type of this FilterValue.  # noqa: E501
        :type: str
        """

        self._agg_type = agg_type

    @property
    def filter_name(self):
        """Gets the filter_name of this FilterValue.  # noqa: E501


        :return: The filter_name of this FilterValue.  # noqa: E501
        :rtype: str
        """
        return self._filter_name

    @filter_name.setter
    def filter_name(self, filter_name):
        """Sets the filter_name of this FilterValue.


        :param filter_name: The filter_name of this FilterValue.  # noqa: E501
        :type: str
        """

        self._filter_name = filter_name

    @property
    def key(self):
        """Gets the key of this FilterValue.  # noqa: E501


        :return: The key of this FilterValue.  # noqa: E501
        :rtype: str
        """
        return self._key

    @key.setter
    def key(self, key):
        """Sets the key of this FilterValue.


        :param key: The key of this FilterValue.  # noqa: E501
        :type: str
        """

        self._key = key

    @property
    def label(self):
        """Gets the label of this FilterValue.  # noqa: E501


        :return: The label of this FilterValue.  # noqa: E501
        :rtype: str
        """
        return self._label

    @label.setter
    def label(self, label):
        """Sets the label of this FilterValue.


        :param label: The label of this FilterValue.  # noqa: E501
        :type: str
        """

        self._label = label

    @property
    def name(self):
        """Gets the name of this FilterValue.  # noqa: E501


        :return: The name of this FilterValue.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this FilterValue.


        :param name: The name of this FilterValue.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def values(self):
        """Gets the values of this FilterValue.  # noqa: E501


        :return: The values of this FilterValue.  # noqa: E501
        :rtype: list[str]
        """
        return self._values

    @values.setter
    def values(self, values):
        """Sets the values of this FilterValue.


        :param values: The values of this FilterValue.  # noqa: E501
        :type: list[str]
        """

        self._values = values

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(FilterValue, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FilterValue):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
