# coding: utf-8

"""
    Sematext Cloud API

    API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.  # noqa: E501

    OpenAPI spec version: v3

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class GenericApiResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'data': 'object',
        'errors': 'list[Error]',
        'message': 'str',
        'success': 'bool'
    }

    attribute_map = {
        'data': 'data',
        'errors': 'errors',
        'message': 'message',
        'success': 'success'
    }

    def __init__(self, data=None, errors=None, message=None, success=None):  # noqa: E501
        """GenericApiResponse - a model defined in Swagger"""  # noqa: E501

        self._data = None
        self._errors = None
        self._message = None
        self._success = None
        self.discriminator = None

        if data is not None:
            self.data = data
        if errors is not None:
            self.errors = errors
        if message is not None:
            self.message = message
        if success is not None:
            self.success = success

    @property
    def data(self):
        """Gets the data of this GenericApiResponse.  # noqa: E501

        Contains actual data when response is successful. Key and Value is specific to each endpoint  # noqa: E501

        :return: The data of this GenericApiResponse.  # noqa: E501
        :rtype: object
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this GenericApiResponse.

        Contains actual data when response is successful. Key and Value is specific to each endpoint  # noqa: E501

        :param data: The data of this GenericApiResponse.  # noqa: E501
        :type: object
        """

        self._data = data

    @property
    def errors(self):
        """Gets the errors of this GenericApiResponse.  # noqa: E501


        :return: The errors of this GenericApiResponse.  # noqa: E501
        :rtype: list[Error]
        """
        return self._errors

    @errors.setter
    def errors(self, errors):
        """Sets the errors of this GenericApiResponse.


        :param errors: The errors of this GenericApiResponse.  # noqa: E501
        :type: list[Error]
        """

        self._errors = errors

    @property
    def message(self):
        """Gets the message of this GenericApiResponse.  # noqa: E501


        :return: The message of this GenericApiResponse.  # noqa: E501
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this GenericApiResponse.


        :param message: The message of this GenericApiResponse.  # noqa: E501
        :type: str
        """

        self._message = message

    @property
    def success(self):
        """Gets the success of this GenericApiResponse.  # noqa: E501


        :return: The success of this GenericApiResponse.  # noqa: E501
        :rtype: bool
        """
        return self._success

    @success.setter
    def success(self, success):
        """Sets the success of this GenericApiResponse.


        :param success: The success of this GenericApiResponse.  # noqa: E501
        :type: bool
        """

        self._success = success

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GenericApiResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GenericApiResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
