# coding: utf-8

"""
    Sematext Cloud API

    API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.  # noqa: E501

    OpenAPI spec version: v3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TokenDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'created_at': 'datetime',
        'enabled': 'bool',
        'id': 'int',
        'name': 'str',
        'readable': 'bool',
        'token': 'str',
        'writeable': 'bool'
    }

    attribute_map = {
        'created_at': 'createdAt',
        'enabled': 'enabled',
        'id': 'id',
        'name': 'name',
        'readable': 'readable',
        'token': 'token',
        'writeable': 'writeable'
    }

    def __init__(self, created_at=None, enabled=None, id=None, name=None, readable=None, token=None, writeable=None):  # noqa: E501
        """TokenDto - a model defined in Swagger"""  # noqa: E501
        self._created_at = None
        self._enabled = None
        self._id = None
        self._name = None
        self._readable = None
        self._token = None
        self._writeable = None
        self.discriminator = None
        if created_at is not None:
            self.created_at = created_at
        if enabled is not None:
            self.enabled = enabled
        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if readable is not None:
            self.readable = readable
        if token is not None:
            self.token = token
        if writeable is not None:
            self.writeable = writeable

    @property
    def created_at(self):
        """Gets the created_at of this TokenDto.  # noqa: E501


        :return: The created_at of this TokenDto.  # noqa: E501
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this TokenDto.


        :param created_at: The created_at of this TokenDto.  # noqa: E501
        :type: datetime
        """

        self._created_at = created_at

    @property
    def enabled(self):
        """Gets the enabled of this TokenDto.  # noqa: E501


        :return: The enabled of this TokenDto.  # noqa: E501
        :rtype: bool
        """
        return self._enabled

    @enabled.setter
    def enabled(self, enabled):
        """Sets the enabled of this TokenDto.


        :param enabled: The enabled of this TokenDto.  # noqa: E501
        :type: bool
        """

        self._enabled = enabled

    @property
    def id(self):
        """Gets the id of this TokenDto.  # noqa: E501


        :return: The id of this TokenDto.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this TokenDto.


        :param id: The id of this TokenDto.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this TokenDto.  # noqa: E501


        :return: The name of this TokenDto.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this TokenDto.


        :param name: The name of this TokenDto.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def readable(self):
        """Gets the readable of this TokenDto.  # noqa: E501


        :return: The readable of this TokenDto.  # noqa: E501
        :rtype: bool
        """
        return self._readable

    @readable.setter
    def readable(self, readable):
        """Sets the readable of this TokenDto.


        :param readable: The readable of this TokenDto.  # noqa: E501
        :type: bool
        """

        self._readable = readable

    @property
    def token(self):
        """Gets the token of this TokenDto.  # noqa: E501


        :return: The token of this TokenDto.  # noqa: E501
        :rtype: str
        """
        return self._token

    @token.setter
    def token(self, token):
        """Sets the token of this TokenDto.


        :param token: The token of this TokenDto.  # noqa: E501
        :type: str
        """

        self._token = token

    @property
    def writeable(self):
        """Gets the writeable of this TokenDto.  # noqa: E501


        :return: The writeable of this TokenDto.  # noqa: E501
        :rtype: bool
        """
        return self._writeable

    @writeable.setter
    def writeable(self, writeable):
        """Sets the writeable of this TokenDto.


        :param writeable: The writeable of this TokenDto.  # noqa: E501
        :type: bool
        """

        self._writeable = writeable

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TokenDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TokenDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
