# coding: utf-8

"""
    Sematext Cloud API

    API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.  # noqa: E501

    OpenAPI spec version: v3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class UpdatePlanResponseDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'events': 'list[EventDto]',
        'plan_id': 'int'
    }

    attribute_map = {
        'events': 'events',
        'plan_id': 'planId'
    }

    def __init__(self, events=None, plan_id=None):  # noqa: E501
        """UpdatePlanResponseDto - a model defined in Swagger"""  # noqa: E501
        self._events = None
        self._plan_id = None
        self.discriminator = None
        if events is not None:
            self.events = events
        if plan_id is not None:
            self.plan_id = plan_id

    @property
    def events(self):
        """Gets the events of this UpdatePlanResponseDto.  # noqa: E501


        :return: The events of this UpdatePlanResponseDto.  # noqa: E501
        :rtype: list[EventDto]
        """
        return self._events

    @events.setter
    def events(self, events):
        """Sets the events of this UpdatePlanResponseDto.


        :param events: The events of this UpdatePlanResponseDto.  # noqa: E501
        :type: list[EventDto]
        """

        self._events = events

    @property
    def plan_id(self):
        """Gets the plan_id of this UpdatePlanResponseDto.  # noqa: E501


        :return: The plan_id of this UpdatePlanResponseDto.  # noqa: E501
        :rtype: int
        """
        return self._plan_id

    @plan_id.setter
    def plan_id(self, plan_id):
        """Sets the plan_id of this UpdatePlanResponseDto.


        :param plan_id: The plan_id of this UpdatePlanResponseDto.  # noqa: E501
        :type: int
        """

        self._plan_id = plan_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UpdatePlanResponseDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UpdatePlanResponseDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
